name: release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup go 1.21
        uses: actions/setup-go@v4.1.0
        with: { go-version: '1.21' }

      - name: Checkout code
        uses: actions/checkout@v3.5.3
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.4.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}